### ISSUE TITLE
Milestone 1: Pseudocode

### ISSUE THREAD

**Issue by mlesmenio** [federatedbookkeeping/task-tracking#11]
High level version of the code to be developed

**Comment by michielbdejong** [comment]
Will you write this for CYB-based nodes or also for WikiSuite-based nodes and Timeld-based nodes?

**Comment by mlesmenio** [comment]
Explain the similarities specify and then specify the details for each.

**Comment by michielbdejong** [comment]
See https://github.com/federatedbookkeeping/research/blob/main/Article/Article.pdf and https://github.com/pondersource/CYB/tree/main/Manuel_file_dump
