### ISSUE TITLE
Milestone 1: Article (Current iteration)

### ISSUE THREAD

**Issue by mlesmenio** [federatedbookkeeping/task-tracking#13]
What we intend to implement is this project. The longest and most detailed section of this article. To include:

1. Considerations about privacy, transparency, integrity, etc. and implications for this iteration.
2. Implementation details:
2.1 Data sharing modes
2.2 Different types of nodes
2.3 Different use cases
2.4 Different topologies
2.5 Federation protocol
2.6 Conflict resolution
2.7 Data duplication
2.8 Network disconnects
2.9 Message storms
2.10 Routing changes
2.11 Digital signatures
2.12 Live data sharing
2.13 Federation monitoring

**Comment by michielbdejong** [comment]
See https://github.com/federatedbookkeeping/research/blob/main/Article/Article.pdf and https://github.com/pondersource/CYB/tree/main/Manuel_file_dump
