### ISSUE TITLE
Storing UUIDs on GitHub issues

### ISSUE THREAD

**Issue by michielbdejong** [federatedbookkeeping/task-tracking#32]
I've got the bridgeBot with LriMap working well now.
Turned out that DXOS wasn't really helping us much, and neither was Cambria (translating fields, but not LRIs)

So far Tiki and GitHub are supported, although Tiki Push is not fully tested yet, and the whole system needs more testing in general

That brings us to the next big topic, which is very visible during debugging: When you wipe out the database, all issues get duplicated, because if there are `n` issues, each mirrored in `m` replicas, then BridgeBot thinks those are all originals, so it will create `n * (m-1)` duplicate issues. This can be mitigated if we store the UUID on synced issues (issues that are a copy of a remote issue). For Tiki and Jira we can add a custom field for this. For GitHub we should probably insert a comment. Ah, can you actually hide text in a comment? Let's try: "" is that visible? -> looks like it's not, great!

**Comment by michielbdejong** [comment]
This comment has:
```
<!--- BridgeBot comment ID: 5f6aa6b1-d231-48f4-bff5-3f7324f5da4d -->
```
as its first body line :)

**Comment by kroky** [comment]
With Timesheets, we added a unique URI to dereference duplicates. I will add that to Tasks tracker as well from Tiki side.

**Comment by michielbdejong** [comment]
<img width="842" alt="Screenshot 2024-06-28 at 11 21 14" src="https://github.com/federatedbookkeeping/task-tracking/assets/408412/b1de3c69-1fdc-42f1-86fa-71fe53c18a59">
