### ISSUE TITLE
creating issues in tracker 3

### ISSUE THREAD

**Issue by michielbdejong** [federatedbookkeeping/task-tracking#37]
Sent:
```
{
  status: 'o',
  syntax: 'tiki',
  trackerId: '3',
  ins_27: 'what is required here',
  ins_28: '',
  ins_31: '',
  ins_37: ''
}
```
To https://timesheet.dev4.evoludata.com/api/trackers/3
Received:
```
{
  code: 409,
  errortitle: '<!--field[name]-->Field Required',
  message: '<!--field[name]-->Field Required'
}
```

@kroky can you produce an error response that details *which* field was missing?

**Comment by michielbdejong** [comment]
I looked at what the web interface sends; adding:
* ticket=n_kKu2qtvdpsIEILiX5jl6k6YX_t-j4sIrOPR7APyj0
* status=o&ins_27=a+new+issue
* mode_wysiwyg=
* mode_normal=
* syntax=tiki
* ins_28=
* wysiwyg=n
* ins_29=
* ins_30=
* del_30=
* ins_31=log+it
* ins_32%5B%5D=
* ins_33%5B%5D=michielbdejong
* ins_33%5B%5D=
* ins_34%5Bobjects%5D=
* skipRefresh=
* refreshMeta=
* refreshObject=

To see of any of those are the apparently missing field.

**Comment by michielbdejong** [comment]
Hm, same issue still:
Sent:
```
{
  status: 'o',
  syntax: 'tiki',
  trackerId: '3',
  ins_27: 'what is required here',
  ins_28: '',
  ins_31: 'log it',
  ins_37: '',
  ticket: 'n_kKu2qtvdpsIEILiX5jl6k6YX_t-j4sIrOPR7APyj0',
  mode_wysiwyg: '',
  mode_normal: '',
  wysiwyg: 'n',
  ins_29: '',
  ins_30: '',
  del_30: '',
  'ins_32%5B%5D': '',
  'ins_33%5B%5D': '',
  'ins_34%5Bobjects%5D': '',
  skipRefresh: '',
  refreshMeta: '',
  refreshObject: ''
}
```
To https://timesheet.dev4.evoludata.com/api/trackers/3

Received
```
{
  code: 409,
  errortitle: '<!--field[name]-->Field Required',
  message: '<!--field[name]-->Field Required'
}

**Comment by kroky** [comment]
This endpoint is used to update the tracker itself - the name field is required when you want to update a tracker. I think you want to create tracker items, use this endpoint:

POST https://timesheet.dev4.evoludata.com/api/trackers/3/items
